displayName=Shades of Mort'ton
author=Nicole McG
description=Adds quality of life improvements to the Shades of Mort'ton minigame
tags=shades,mort'ton,minigame,firemaking,prayer,pyre,chest
plugins=com.shadesofmorton.ShadesOfMortonPlugin
build=standard
